language: cpp
sudo: false
env:
  - LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/tests/:$TRAVIS_BUILD_DIR:$LD_LIBRARY_PATH
  - DYLD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/tests/:$TRAVIS_BUILD_DIR:$DYLD_LIBRARY_PATH
script:
  - ./make.sh
  - make check
  - cd bindings/python && make check
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
