language: cpp
sudo: false
before_script:
  - wget https://github.com/groundx/capstonefuzz/raw/master/corpus/corpus-libFuzzer-capstone_fuzz_disasmnext-latest.zip
  - unzip -q corpus-libFuzzer-capstone_fuzz_disasmnext-latest.zip -d suite/fuzz
script:
  - ./make.sh
  - make check
  - sudo make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp libcapstone.so.* bindings/python/libcapstone.so; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp libcapstone.*.dylib bindings/python/libcapstone.dylib; fi
  - if [[ "$NOPYTEST" != "true" ]]; then pushd bindings/python && make check && popd; fi
  - if [[ "$NOPYTEST" != "true" ]]; then pushd suite/cstest && make && popd; fi
  - if [[ "$NOPYTEST" != "true" ]]; then pushd suite/cstest && python cstest_report.py -D -t build/cstest -d ../MC && popd; fi
  - if [[ "$NOPYTEST" != "true" ]]; then pushd suite/cstest && python cstest_report.py -D -t build/cstest -f issues.cs && popd; fi
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - libcmocka-dev
matrix:
  include:
    - language: android
      install: echo y | sdkmanager "ndk-bundle"
      env: ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle NDK=$ANDROID_NDK_HOME
      script: ./make.sh cross-android arm
    - language: android
      install: echo y | sdkmanager "ndk-bundle"
      env: ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle NDK=$ANDROID_NDK_HOME
      script: ./make.sh cross-android arm64
    - name: fuzza
      env: ASAN_OPTIONS=detect_leaks=0 CXXFLAGS="-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address" CFLAGS="-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address" LDFLAGS="-fsanitize=address" NOPYTEST=true
      compiler: clang
      os: linux
    - name: fuzzm
      env: CXXFLAGS="-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=memory" CFLAGS="-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=memory" LDFLAGS="-fsanitize=memory" NOPYTEST=true
      compiler: clang
      os: linux
    - name: fuzzu
      env: CXXFLAGS="-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=undefined" CFLAGS="-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=undefined -fno-sanitize-recover=undefined,integer" LDFLAGS="-fsanitize=undefined" NOPYTEST=true
      compiler: clang
      os: linux
